import Link from 'next/link';
import { ArrowRight, LockKeyhole, FolderOpen, Search, Share2, FileText, Shield, HardDrive, Upload, Cloud } from 'lucide-react';
import { Logo } from '@/components/Logo';

const features = [
  ['Private storage', 'Keep your file library organized in a personal workspace.', LockKeyhole],
  ['Folders that fit', 'Build a clear structure and find items quickly.', FolderOpen],
  ['Fast uploads', 'Bring files in from desktop or mobile.', Upload],
  ['Secure sharing', 'Create revocable links with optional passwords and expiry.', Share2],
  ['Useful previews', 'Preview common image, text, and document formats.', FileText],
  ['Search that helps', 'Find files by name and category.', Search],
  ['Trash & recovery', 'Recover items you have recently deleted.', HardDrive],
  ['Provider choice', 'Keep file bytes behind a server-side storage adapter.', Cloud],
] as const;

export default function Home() {
  return <main>
    <header className="mx-auto flex max-w-7xl items-center justify-between px-6 py-5"><Logo/><nav className="hidden items-center gap-7 text-sm text-muted md:flex"><a href="#features">Features</a><a href="#security">Security</a><a href="#how">How it works</a></nav><div className="flex items-center gap-4 text-sm"><Link href="/login" className="text-muted">Log in</Link><Link href="/register" className="rounded-lg bg-indigo-500 px-4 py-2.5 font-medium">Get started <ArrowRight size={15} className="ml-1 inline"/></Link></div></header>
    <section className="mx-auto grid max-w-7xl gap-14 px-6 pb-24 pt-20 md:grid-cols-[1.1fr_.9fr] md:items-center"><div><p className="mb-5 inline-flex items-center gap-2 rounded-full border border-line px-3 py-1.5 text-xs text-muted"><span className="h-2 w-2 rounded-full bg-emerald-400"/>Personal file storage, on your terms</p><h1 className="max-w-2xl text-5xl font-semibold leading-tight tracking-tight md:text-7xl">Your files. Your cloud. <span className="text-brand">Your control.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-muted">A calm, private space for your files. CloudNest keeps your library organized while storage stays behind your chosen provider.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/register" className="rounded-lg bg-indigo-500 px-5 py-3 font-medium">Get started <ArrowRight size={16} className="ml-2 inline"/></Link><a href="#features" className="rounded-lg border border-line px-5 py-3">Explore CloudNest</a></div></div>
      <div className="surface overflow-hidden rounded-2xl p-5 shadow-2xl"><div className="mb-5 flex items-center justify-between"><div><p className="text-xs text-muted">WORKSPACE</p><h2 className="mt-1 font-medium">My Drive</h2></div><div className="rounded-lg border border-line px-3 py-2 text-xs text-muted">Search files</div></div><div className="grid grid-cols-3 gap-3">{[0,1,2].map(i=><div key={i} className="rounded-xl border border-line bg-ink p-4"><FolderOpen className="text-muted" size={20}/><div className="mt-8 h-2 w-16 rounded bg-line"/><div className="mt-2 h-2 w-10 rounded bg-line"/></div>)}</div><div className="mt-4 flex min-h-24 items-center justify-center rounded-xl border border-dashed border-line text-sm text-muted">Your files appear here</div><div className="mt-4 rounded-lg border border-line p-3"><div className="flex justify-between text-xs"><span className="text-muted">Storage usage</span><span>Calculated from your library</span></div><div className="mt-2 h-1.5 rounded bg-line"/></div></div>
    </section>
    <section id="features" className="border-y border-line bg-[#131720] px-6 py-20"><div className="mx-auto max-w-7xl"><p className="text-xs font-semibold uppercase tracking-[.2em] text-brand">A simpler home for your files</p><h2 className="mt-3 text-3xl font-semibold">Everything you need to stay organized.</h2><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{features.map(([title,desc,Icon])=><article key={title} className="surface rounded-xl p-5"><Icon size={21} className="text-brand"/><h3 className="mt-5 font-medium">{title}</h3><p className="mt-2 text-sm leading-6 text-muted">{desc}</p></article>)}</div></div></section>
    <section id="security" className="mx-auto grid max-w-7xl gap-10 px-6 py-20 md:grid-cols-2"><div><Shield className="text-brand"/><h2 className="mt-4 text-3xl font-semibold">Security starts with clear boundaries.</h2></div><p className="leading-7 text-muted">Account passwords are hashed, sessions are stored server-side, and file access is checked against your account. Telegram, when configured, is only a storage provider; its credentials stay on the server. CloudNest does not currently provide end-to-end encryption or security certifications.</p></section>
    <section id="how" className="border-y border-line bg-[#131720] px-6 py-20"><div className="mx-auto max-w-7xl"><h2 className="text-3xl font-semibold">How CloudNest works</h2><div className="mt-8 grid gap-4 md:grid-cols-4">{['Upload from your device','CloudNest checks access and metadata','Storage provider keeps the file bytes','Manage, preview, and share from anywhere'].map((x,i)=><div className="surface rounded-xl p-5" key={x}><p className="text-sm text-brand">0{i+1}</p><p className="mt-3 leading-6">{x}</p></div>)}</div></div></section>
    <footer className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-6 px-6 py-8 text-sm text-muted"><Logo/><div className="flex flex-wrap gap-5">{['privacy','terms','cookies','security','acceptable-use','contact'].map(x=><Link href={`/${x}`} key={x}>{x[0].toUpperCase()+x.slice(1)}</Link>)}</div><span>© {new Date().getFullYear()} CloudNest</span></footer>
  </main>;
}
